### ISSUE TITLE
v0.6.2 Error @73dm3l4p4: Cannot load module

### ISSUE THREAD

**Issue by juniorh** [lmenezes/cerebro#107]
Hi,

I just try cerebro-0.6.2 but it failed to start:

```
$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

$ bin/cerebro -Dhttp.port=1234 -Dhttp.address=127.0.0.1 -v
# Executing command line:
java
-Duser.dir=/opt/cerebro
-Dhttp.port=1234
-Dhttp.address=127.0.0.1
-cp

-jar
/opt/cerebro/lib/cerebro.cerebro-0.6.2-launcher.jar

Oops, cannot start the server.
@73dm4hj80: Cannot load module
        at play.api.inject.Modules$.play$api$inject$Modules$$constructModule(Module.scala:147)
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:114)
        at play.api.inject.Modules$$anonfun$locate$1.apply(Module.scala:113)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:316)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at play.api.inject.Modules$.locate(Module.scala:113)
        at play.api.inject.guice.GuiceableModule$.loadModules(GuiceInjectorBuilder.scala:272)
        at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$10$1.apply(GuiceApplicationBuilder.scala:30)
        at play.api.inject.guice.GuiceApplicationBuilder$$anonfun$$lessinit$greater$default$10$1.apply(GuiceApplicationBuilder.scala:30)
        at play.api.inject.guice.GuiceApplicationBuilder.applicationModule(GuiceApplicationBuilder.scala:109)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:47)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
Caused by: java.lang.ClassNotFoundException: elastic.ElasticModule
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at play.api.inject.Modules$$anonfun$locate$1$$anonfun$apply$1.apply(Module.scala:115)
        at play.api.inject.Modules$$anonfun$locate$1$$anonfun$apply$1.apply(Module.scala:115)
        at play.api.inject.Modules$.play$api$inject$Modules$$constructModule(Module.scala:121)
        ... 21 more
```

This error doesn't exist on v0.6.1

**Comment by lmenezes** [comment]
@juniorh It seems your config file might be outdated. There were quite a few changes on the config file(mostly to make it simpler and hide internal configs). In particular I think you need to remove these 2 lines, as they are no longer necessary:
```
play.modules.enabled += "controllers.auth.Module"
play.modules.enabled += "elastic.ElasticModule"
```
