### ISSUE TITLE
"No handler found for uri" on latest release

### ISSUE THREAD

**Issue by mikemadisonweb** [lmenezes/cerebro#108]
Hello,
I think your app is very promising, but I can't get it work. I have Elasticsearch 5.2.2 in a docker container and I had downloaded cerebro latest release (0.6.3), unpack and executed it locally. All seemed fine but when I entered URL to Elasicsearch i got an error:
"error": "No handler found for uri [//_cluster/state/master_node,routing_table,routing_nodes,blocks] and method [GET]"
When I tried to connect to Elasticsearch by myself it works and if I try requested URL without double slash it opens as expected too.
I also tried version 0.5.0, web interface opens on it and connected to ES successfully, but throws an error in console:
PlayDefaultUpstreamHandler - Exception caught in Netty
java.lang.IllegalArgumentException: invalid version format: ENCODING="ISO-8859-1"?>
	at org.jboss.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:94) ~[io.netty.netty-3.10.4.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62) ~[io.netty.netty-3.10.4.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75) ~[io.netty.netty-3.10.4.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191) ~[io.netty.netty-3.10.4.Final.jar:na]
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102) ~[io.netty.netty-3.10.4.Final.jar:na]

**Comment by lmenezes** [comment]
@mikemadisonweb I guess your problem is you are adding an **/** to the ES url, so the route requested is //_cluster, instead of simply /_cluster.

In previous versions ES didn't care about this, so it was never a concern. I will add a check to remove  fix this in the app, but for now just remove the extra / and it should be fine :)

**Comment by damienalexandre** [comment]
Gosh, just had the same issue and you are right, removing the extra `/` at the end fix the error. :+1:

**Comment by LeoMXIBM** [comment]
Hi lmenezes
I have the same problem, but I don't know where I can remove the /, can you tell me where? please
