### ISSUE TITLE
java.lang.NullPointerException: scheme

### ISSUE THREAD

**Issue by nouuid** [lmenezes/cerebro#116]
cerebro-0.6.4.tgz is installed. In Cerebro homeview, I connected an address -.-.-.-:9201, it continually reports errors: Error while loading data.

The application.log showed:
2017-04-01 11:09:39,762 - [ERROR] - from application in application-akka.actor.default-dispatcher-13 
Error processing request [path: /overview, body: {"host":"-.-.-.-:9201"}]
java.lang.NullPointerException: scheme
	at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23)
	at org.asynchttpclient.uri.Uri.<init>(Uri.java:63)
	at org.asynchttpclient.uri.Uri.create(Uri.java:38)
	at org.asynchttpclient.uri.Uri.create(Uri.java:31)
	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:148)
	at play.api.libs.ws.ahc.AhcWSRequest.buildRequest(AhcWS.scala:252)
	at play.api.libs.ws.ahc.AhcWSRequest$$anon$2.execute(AhcWS.scala:166)
	at play.api.libs.ws.ahc.AhcWSRequest.execute(AhcWS.scala:168)
	at elastic.HTTPElasticClient.execute(HTTPElasticClient.scala:308)
	at elastic.HTTPElasticClient.clusterState(HTTPElasticClient.scala:22)
	at controllers.ClusterOverviewController$$anonfun$index$1.apply(ClusterOverviewController.scala:20)
	at controllers.ClusterOverviewController$$anonfun$index$1.apply(ClusterOverviewController.scala:17)
	at controllers.BaseController$$anonfun$process$1.apply(BaseController.scala:23)
	at controllers.BaseController$$anonfun$process$1.apply(BaseController.scala:21)
	at controllers.auth.AuthAction.invokeBlock(AuthAction.scala:28)
	at controllers.auth.AuthAction.invokeBlock(AuthAction.scala:12)
	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
	at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by nouuid** [comment]
After I configure the item "hosts" in application.conf, it works.

**Comment by excalq** [comment]
I'm actually observing the same issue, but cannot connect it with anything in my config files. When running the Cerebro application, I get errors to stderr, even though the application works generally. It's worth noting that `Prod-ES-Cluster` is no longer in my config hosts. I'm guessing this is in the SQLite Database? Can you advise what's going on here?

```
user@host:/opt/cerebro-0.7.2$ sudo bin/cerebro -Dhttp.port=9200 -Dhttp.address=0.0.0.0
[warn] application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0.0.0.0:9200
[error] application - Error processing request [path: /navbar, body: {"host":"Prod-ES-Cluster"}]
java.lang.NullPointerException: scheme
	at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23)
	at org.asynchttpclient.uri.Uri.<init>(Uri.java:63)
	at org.asynchttpclient.uri.Uri.create(Uri.java:38)
	at org.asynchttpclient.uri.Uri.create(Uri.java:31)
	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:148)
[error] application - Error processing request [path: /cluster_changes, body: {"host":"Prod-ES-Cluster"}]
java.lang.NullPointerException: scheme
	at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23)
	at org.asynchttpclient.uri.Uri.<init>(Uri.java:63)
	at org.asynchttpclient.uri.Uri.create(Uri.java:38)
	at org.asynchttpclient.uri.Uri.create(Uri.java:31)
	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:148)
```

**Comment by excalq** [comment]
Deleting the cerebro.db SQLite DB does not resolve the problem. Strangely, grepping for `Prod-ES-Cluster` in the Cerebro install directory or in all of `/etc`, does not show any files (except logs) with this host/cluster name. Strange.

**Comment by excalq** [comment]
So it turned out that I had an old tab open in my browser with `http://cerebro/#/overview?host=Prod-ES-Cluster` open, which was auto-refreshing and causing those error log entries. Sorry for the noise, but perhaps someone will find this useful in their debugging.
