### ISSUE TITLE
Cannot start cerebro on OS X

### ISSUE THREAD

**Issue by kdambekalns** [lmenezes/cerebro#123]
All I get after downloading 0.6.4 is this:

```$ bin/cerebro
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:791)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	at play.core.server.ProdServerStart$.readServerConfigSettings(ProdServerStart.scala:76)
	at play.core.server.ProdServerStart$.start(ProdServerStart.scala:37)
	at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
	at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

```
$ java -version
java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b12)
Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)
```

As a noob regarding Java, what should I do?

**Comment by lmenezes** [comment]
Upgrade to java 8, which is a requirement ;)

**Comment by kdambekalns** [comment]
Ok, that fooled me, leaving it here for others to find… :)

The "Java Control Panel" said it was Java 8, but on the CLI it wasn't. Installed Java 8 again, now it works. Thanks!
