### ISSUE TITLE
RPM and Deb Packages

### ISSUE THREAD

**Issue by ruben-herold** [lmenezes/cerebro#149]
hi,

as far I could see there is a pending pull request that makes it possible that you
can easily release deb and rpm files. It would be nice to have this.

**Comment by thalesfsp** [comment]
@lmenezes ?

**Comment by ruben-herold** [comment]
It seems that it is merged into master but it seems not be completed:

error] `rpmVendor in Rpm` is empty.  Please provide a valid vendor for the rpm SPEC.
java.lang.RuntimeException: There are issues with the rpm spec data.
	at scala.sys.package$.error(package.scala:27)
name := "cerebro"

maintainer := "Leonardo Menezes <leonardo.menezes@xing.com>"

version := "0.6.5"

scalaVersion := "2.11.8"

libraryDependencies ++= Seq(
  "com.typesafe.play" %% "play"                    % "2.5.10",
  "com.typesafe.play" %% "play-ws"                 % "2.5.10",
	at com.typesafe.sbt.packager.rpm.RpmSpec.validate(RpmMetadata.scala:168)
	at com.typesafe.sbt.packager.rpm.RpmPlugin$$anonfun$projectSettings$46.apply(RpmPlugin.scala:160)
	at com.typesafe.sbt.packager.rpm.RpmPlugin$$anonfun$projectSettings$46.apply(RpmPlugin.scala:157)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (rpm:packageBin) There are issues with the rpm spec data.
[error] Total time: 33 s, completed 06.06.2017 13:15:41

**Comment by blacksd** [comment]
Hi,
I've been able to compile an RPM successfully using [these great directions on SO](https://stackoverflow.com/questions/28749054/sbt-native-packager-and-rpm-how-do-i-set-required-parameters). It boils down to have these settings:
```
rpmRelease := "1"

rpmVendor := "lmenezes"

rpmUrl := Some("http://github.com/lmenezes/cerebro")

rpmLicense := Some("BSD")
```

in a file called `rpmSettings.sbt` - or any_other_name.sbt, really - at the same level of `build.sbt` (in the root directory). Keep the blank lines. 

@lmenezes I've included the BSD license in the specs, but I'm not sure which one this project has. Could you clarify?

**Comment by Reiner030** [comment]
@blacksd : From README of this repo:

> cerebro is an open source**(MIT License)** elasticsearch web admin tool built using Scala, Play Framework, AngularJS and Bootstrap.

**Comment by sihil** [comment]
@lmenezes Would you be willing to release DEB and RPM packages along side the tarballs when you do a release?

**Comment by zabojcaspamu** [comment]
@sihil this is rpm for cerebro
https://github.com/zabojcaspamu/cerebro-rpm

**Comment by moliware** [comment]
Hi!

Thanks for the comments I submitted #308 to have the ability to create rpm/deb packages.

**Comment by wols** [comment]
See also #87
