### ISSUE TITLE
overview exception

### ISSUE THREAD

**Issue by blalor** [lmenezes/cerebro#150]
Cerebro 0.6.5, ES 5.1.  I think the cluster's in a weird state, but it's hard to tell because Cerebro can't render the overview. :-)

```
[error] application -

! @74577fp9b - Internal server error, for (POST) [/overview] ->

play.api.UnexpectedException: Unexpected exception[JsResultException: JsResultException(errors:List((,List(ValidationError(List('Kd_RSnvIQoGEjfSmlItR2w' is undefined on object: {"yRg5Lt1iQ6GcPW1ocYSAYg":{"timestamp":1495547920796,"name":"f1c509b2-cd13-4970-b111-4b0faa54d0d8","transport_address":"10.112.3.27:9300","host":"10.112.3.27","ip":"10.112.3.27:9300","roles":["master","data","ingest"],"os":{"timestamp":1495547920798,"cpu":{"percent":86,"load_average":{"1m":5.82,"5m":5,"15m":2.83}},"mem":{"total":"29.9gb","total_in_bytes":32168050688,"free":"3.7gb","free_in_bytes":4029800448,"used":"26.2gb","used_in_bytes":28138250240,"free_percent":13,"used_percent":87},"swap":{"total":"0b","total_in_bytes":0,"free":"0b","free_in_bytes":0,"used":"0b","used_in_bytes":0},"cgroup":{"cpuacct":{"control_group":"/machine.slice/nomad-f1c509b2-cd13-4970-b111-4b0faa54d0d8.scope","usage_nanos":816331580543},"cpu":{"control_group":"/machine.slice/nomad-f1c509b2-cd13-4970-b111-4b0faa54d0d8.scope","cfs_period_micros":100000,"cfs_quota_micros":-1,"stat":{"number_of_elapsed_periods":0,"number_of_times_throttled":0,"time_throttled_nanos":0}}}},"process":{"timestamp":1495547920798,"open_file_descriptors":335,"max_file_descriptors":65536,"cpu":{"percent":58,"total":"17.8m","total_in_millis":1071720},"mem":{"total_virtual":"21.9gb","total_virtual_in_bytes":23520862208}},"jvm":{"timestamp":1495547920798,"uptime":"10.8m","uptime_in_millis":650670,"mem":{"heap_used":"1.9gb","heap_used_in_bytes":2126631712,"heap_used_percent":15,"heap_committed":"12.6gb","heap_committed_in_bytes":13596622848,"heap_max":"12.6gb","heap_max_in_bytes":13596622848,"non_heap_used":"98.6mb","non_heap_used_in_bytes":103435688,"non_heap_committed":"103.4mb","non_heap_committed_in_bytes":108478464,"pools":{"young":{"used":"113.4mb","used_in_bytes":118959336,"max":"266.2mb","max_in_bytes":279183360,"peak_used":"266.2mb","peak_used_in_bytes":279183360,"peak_max":"266.2mb","peak_max_in_bytes":279183360},"survivor":{"used":"30.4mb","used_in_bytes":31895120,"max":"33.2mb","max_in_bytes":34865152,"peak_used":"33.2mb","peak_used_in_bytes":34865152,"peak_max":"33.2mb","peak_max_in_bytes":34865152},"old":{"used":"1.8gb","used_in_bytes":1975777256,"max":"12.3gb","max_in_bytes":13282574336,"peak_used":"9.3gb","peak_used_in_bytes":10039474360,"peak_max":"12.3gb","peak_max_in_bytes":13282574336}}},"threads":{"count":64,"peak_count":66},"gc":{"collectors":{"young":{"collection_count":742,"collection_time":"48.9s","collection_time_in_millis":48957},"old":{"collection_count":2,"collection_time":"126ms","collection_time_in_millis":126}}},"buffer_pools":{"direct":{"count":89,"used":"140.4mb","used_in_bytes":147259400,"total_capacity":"140.4mb","total_capacity_in_bytes":147259399},"mapped":{"count":676,"used":"5.4gb","used_in_bytes":5832549775,"total_capacity":"5.4gb","total_capacity_in_bytes":5832549775}},"classes":{"current_loaded_count":10469,"total_loaded_count":10486,"total_unloaded_count":17}},"fs":{"timestamp":1495547920799,"total":{"total":"98.3gb","total_in_bytes":105554829312,"free":"91.3gb","free_in_bytes":98049282048,"available":"86.2gb","available_in_bytes":92663791616},"data":[{"path":"/alloc/data/nodes/0","mount":"/alloc (/dev/xvdh)","type":"ext4","total":"98.3gb","total_in_bytes":105554829312,"free":"91.3gb","free_in_bytes":98049282048,"available":"86.2gb","available_in_bytes":92663791616,"spins":"false"}],"io_stats":{"devices":[{"device_name":"xvdh","operations":163788,"read_operations":15,"write_operations":163773,"read_kilobytes":60,"write_kilobytes":10636860}],"total":{"operations":163788,"read_operations":15,"write_operations":163773,"read_kilobytes":60,"write_kilobytes":10636860}}}},"JNleTcs4R7WFZafxpLGpew":{"timestamp":1495547920797,"name":"694d69f3-0e7a-366e-5802-ae99154a6d97","transport_address":"10.112.3.78:9300","host":"10.112.3.78","ip":"10.112.3.78:9300","roles":["master","data","ingest"],"os":{"timestamp":1495547920798,"cpu":{"percent":44,"load_average":{"1m":4.74,"5m":3.59,"15m":1.9}},"mem":{"total":"29.9gb","total_in_bytes":32168050688,"free":"5.2gb","free_in_bytes":5646438400,"used":"24.7gb","used_in_bytes":26521612288,"free_percent":18,"used_percent":82},"swap":{"total":"0b","total_in_bytes":0,"free":"0b","free_in_bytes":0,"used":"0b","used_in_bytes":0},"cgroup":{"cpuacct":{"control_group":"/machine.slice","usage_nanos":23508285615148},"cpu":{"control_group":"/machine.slice","cfs_period_micros":100000,"cfs_quota_micros":-1,"stat":{"number_of_elapsed_periods":0,"number_of_times_throttled":0,"time_throttled_nanos":0}}}},"process":{"timestamp":1495547920799,"open_file_descriptors":318,"max_file_descriptors":65536,"cpu":{"percent":45,"total":"4.5h","total_in_millis":16532200},"mem":{"total_virtual":"23.2gb","total_virtual_in_bytes":24935157760}},"jvm":{"timestamp":1495547920799,"uptime":"16.3h","uptime_in_millis":58947324,"mem":{"heap_used":"3.4gb","heap_used_in_bytes":3744058208,"heap_used_percent":27,"heap_committed":"12.6gb","heap_committed_in_bytes":13596622848,"heap_max":"12.6gb","heap_max_in_bytes":13596622848,"non_heap_used":"112.9mb","non_heap_used_in_bytes":118415736,"non_heap_committed":"118.3mb","non_heap_committed_in_bytes":124080128,"pools":{"young":{"used":"104.2mb","used_in_bytes":109295136,"max":"266.2mb","max_in_bytes":279183360,"peak_used":"266.2mb","peak_used_in_bytes":279183360,"peak_max":"266.2mb","peak_max_in_bytes":279183360},"survivor":{"used":"29.7mb","used_in_bytes":31169568,"max":"33.2mb","max_in_bytes":34865152,"peak_used":"33.2mb","peak_used_in_bytes":34865152,"peak_max":"33.2mb","peak_max_in_bytes":34865152},"old":{"used":"3.3gb","used_in_bytes":3603593504,"max":"12.3gb","max_in_bytes":13282574336,"peak_used":"9.3gb","peak_used_in_bytes":10032111288,"peak_max":"12.3gb","peak_max_in_bytes":13282574336}}},"threads":{"count":70,"peak_count":74},"gc":{"collectors":{"young":{"collection_count":25497,"collection_time":"14.3m","collection_time_in_millis":859780},"old":{"collection_count":9,"collection_time":"607ms","collection_time_in_millis":607}}},"buffer_pools":{"direct":{"count":150,"used":"140.9mb","used_in_bytes":147765959,"total_capacity":"140.9mb","total_capacity_in_bytes":147765958},"mapped":{"count":850,"used":"6.7gb","used_in_bytes":7233063731,"total_capacity":"6.7gb","total_capacity_in_bytes":7233063731}},"classes":{"current_loaded_count":10882,"total_loaded_count":10930,"total_unloaded_count":48}},"fs":{"timestamp":1495547920799,"total":{"total":"98.3gb","total_in_bytes":105554829312,"free":"90.3gb","free_in_bytes":97038004224,"available":"85.3gb","available_in_bytes":91652517888},"data":[{"path":"/alloc/data/nodes/0","mount":"/alloc (/dev/xvdh)","type":"ext4","total":"98.3gb","total_in_bytes":105554829312,"free":"90.3gb","free_in_bytes":97038004224,"available":"85.3gb","available_in_bytes":91652517888,"spins":"false"}],"io_stats":{"devices":[{"device_name":"xvdh","operations":3519864,"read_operations":526,"write_operations":3519338,"read_kilobytes":62660,"write_kilobytes":75869412}],"total":{"operations":3519864,"read_operations":526,"write_operations":3519338,"read_kilobytes":62660,"write_kilobytes":75869412}}}}}),WrappedArray())))))]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(List('Kd_RSnvIQoGEjfSmlItR2w' is undefined on object: {"yRg5Lt1iQ6GcPW1ocYSAYg":{"timestamp":1495547920796,"name":"f1c509b2-cd13-4970-b111-4b0faa54d0d8","transport_address":"10.112.3.27:9300","host":"10.112.3.27","ip":"10.112.3.27:9300","roles":["master","data","ingest"],"os":{"timestamp":1495547920798,"cpu":{"percent":86,"load_average":{"1m":5.82,"5m":5,"15m":2.83}},"mem":{"total":"29.9gb","total_in_bytes":32168050688,"free":"3.7gb","free_in_bytes":4029800448,"used":"26.2gb","used_in_bytes":28138250240,"free_percent":13,"used_percent":87},"swap":{"total":"0b","total_in_bytes":0,"free":"0b","free_in_bytes":0,"used":"0b","used_in_bytes":0},"cgroup":{"cpuacct":{"control_group":"/machine.slice/nomad-f1c509b2-cd13-4970-b111-4b0faa54d0d8.scope","usage_nanos":816331580543},"cpu":{"control_group":"/machine.slice/nomad-f1c509b2-cd13-4970-b111-4b0faa54d0d8.scope","cfs_period_micros":100000,"cfs_quota_micros":-1,"stat":{"number_of_elapsed_periods":0,"number_of_times_throttled":0,"time_throttled_nanos":0}}}},"process":{"timestamp":1495547920798,"open_file_descriptors":335,"max_file_descriptors":65536,"cpu":{"percent":58,"total":"17.8m","total_in_millis":1071720},"mem":{"total_virtual":"21.9gb","total_virtual_in_bytes":23520862208}},"jvm":{"timestamp":1495547920798,"uptime":"10.8m","uptime_in_millis":650670,"mem":{"heap_used":"1.9gb","heap_used_in_bytes":2126631712,"heap_used_percent":15,"heap_committed":"12.6gb","heap_committed_in_bytes":13596622848,"heap_max":"12.6gb","heap_max_in_bytes":13596622848,"non_heap_used":"98.6mb","non_heap_used_in_bytes":103435688,"non_heap_committed":"103.4mb","non_heap_committed_in_bytes":108478464,"pools":{"young":{"used":"113.4mb","used_in_bytes":118959336,"max":"266.2mb","max_in_bytes":279183360,"peak_used":"266.2mb","peak_used_in_bytes":279183360,"peak_max":"266.2mb","peak_max_in_bytes":279183360},"survivor":{"used":"30.4mb","used_in_bytes":31895120,"max":"33.2mb","max_in_bytes":34865152,"peak_used":"33.2mb","peak_used_in_bytes":34865152,"peak_max":"33.2mb","peak_max_in_bytes":34865152},"old":{"used":"1.8gb","used_in_bytes":1975777256,"max":"12.3gb","max_in_bytes":13282574336,"peak_used":"9.3gb","peak_used_in_bytes":10039474360,"peak_max":"12.3gb","peak_max_in_bytes":13282574336}}},"threads":{"count":64,"peak_count":66},"gc":{"collectors":{"young":{"collection_count":742,"collection_time":"48.9s","collection_time_in_millis":48957},"old":{"collection_count":2,"collection_time":"126ms","collection_time_in_millis":126}}},"buffer_pools":{"direct":{"count":89,"used":"140.4mb","used_in_bytes":147259400,"total_capacity":"140.4mb","total_capacity_in_bytes":147259399},"mapped":{"count":676,"used":"5.4gb","used_in_bytes":5832549775,"total_capacity":"5.4gb","total_capacity_in_bytes":5832549775}},"classes":{"current_loaded_count":10469,"total_loaded_count":10486,"total_unloaded_count":17}},"fs":{"timestamp":1495547920799,"total":{"total":"98.3gb","total_in_bytes":105554829312,"free":"91.3gb","free_in_bytes":98049282048,"available":"86.2gb","available_in_bytes":92663791616},"data":[{"path":"/alloc/data/nodes/0","mount":"/alloc (/dev/xvdh)","type":"ext4","total":"98.3gb","total_in_bytes":105554829312,"free":"91.3gb","free_in_bytes":98049282048,"available":"86.2gb","available_in_bytes":92663791616,"spins":"false"}],"io_stats":{"devices":[{"device_name":"xvdh","operations":163788,"read_operations":15,"write_operations":163773,"read_kilobytes":60,"write_kilobytes":10636860}],"total":{"operations":163788,"read_operations":15,"write_operations":163773,"read_kilobytes":60,"write_kilobytes":10636860}}}},"JNleTcs4R7WFZafxpLGpew":{"timestamp":1495547920797,"name":"694d69f3-0e7a-366e-5802-ae99154a6d97","transport_address":"10.112.3.78:9300","host":"10.112.3.78","ip":"10.112.3.78:9300","roles":["master","data","ingest"],"os":{"timestamp":1495547920798,"cpu":{"percent":44,"load_average":{"1m":4.74,"5m":3.59,"15m":1.9}},"mem":{"total":"29.9gb","total_in_bytes":32168050688,"free":"5.2gb","free_in_bytes":5646438400,"used":"24.7gb","used_in_bytes":26521612288,"free_percent":18,"used_percent":82},"swap":{"total":"0b","total_in_bytes":0,"free":"0b","free_in_bytes":0,"used":"0b","used_in_bytes":0},"cgroup":{"cpuacct":{"control_group":"/machine.slice","usage_nanos":23508285615148},"cpu":{"control_group":"/machine.slice","cfs_period_micros":100000,"cfs_quota_micros":-1,"stat":{"number_of_elapsed_periods":0,"number_of_times_throttled":0,"time_throttled_nanos":0}}}},"process":{"timestamp":1495547920799,"open_file_descriptors":318,"max_file_descriptors":65536,"cpu":{"percent":45,"total":"4.5h","total_in_millis":16532200},"mem":{"total_virtual":"23.2gb","total_virtual_in_bytes":24935157760}},"jvm":{"timestamp":1495547920799,"uptime":"16.3h","uptime_in_millis":58947324,"mem":{"heap_used":"3.4gb","heap_used_in_bytes":3744058208,"heap_used_percent":27,"heap_committed":"12.6gb","heap_committed_in_bytes":13596622848,"heap_max":"12.6gb","heap_max_in_bytes":13596622848,"non_heap_used":"112.9mb","non_heap_used_in_bytes":118415736,"non_heap_committed":"118.3mb","non_heap_committed_in_bytes":124080128,"pools":{"young":{"used":"104.2mb","used_in_bytes":109295136,"max":"266.2mb","max_in_bytes":279183360,"peak_used":"266.2mb","peak_used_in_bytes":279183360,"peak_max":"266.2mb","peak_max_in_bytes":279183360},"survivor":{"used":"29.7mb","used_in_bytes":31169568,"max":"33.2mb","max_in_bytes":34865152,"peak_used":"33.2mb","peak_used_in_bytes":34865152,"peak_max":"33.2mb","peak_max_in_bytes":34865152},"old":{"used":"3.3gb","used_in_bytes":3603593504,"max":"12.3gb","max_in_bytes":13282574336,"peak_used":"9.3gb","peak_used_in_bytes":10032111288,"peak_max":"12.3gb","peak_max_in_bytes":13282574336}}},"threads":{"count":70,"peak_count":74},"gc":{"collectors":{"young":{"collection_count":25497,"collection_time":"14.3m","collection_time_in_millis":859780},"old":{"collection_count":9,"collection_time":"607ms","collection_time_in_millis":607}}},"buffer_pools":{"direct":{"count":150,"used":"140.9mb","used_in_bytes":147765959,"total_capacity":"140.9mb","total_capacity_in_bytes":147765958},"mapped":{"count":850,"used":"6.7gb","used_in_bytes":7233063731,"total_capacity":"6.7gb","total_capacity_in_bytes":7233063731}},"classes":{"current_loaded_count":10882,"total_loaded_count":10930,"total_unloaded_count":48}},"fs":{"timestamp":1495547920799,"total":{"total":"98.3gb","total_in_bytes":105554829312,"free":"90.3gb","free_in_bytes":97038004224,"available":"85.3gb","available_in_bytes":91652517888},"data":[{"path":"/alloc/data/nodes/0","mount":"/alloc (/dev/xvdh)","type":"ext4","total":"98.3gb","total_in_bytes":105554829312,"free":"90.3gb","free_in_bytes":97038004224,"available":"85.3gb","available_in_bytes":91652517888,"spins":"false"}],"io_stats":{"devices":[{"device_name":"xvdh","operations":3519864,"read_operations":526,"write_operations":3519338,"read_kilobytes":62660,"write_kilobytes":75869412}],"total":{"operations":3519864,"read_operations":526,"write_operations":3519338,"read_kilobytes":62660,"write_kilobytes":75869412}}}}}),WrappedArray())))))
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:23)
	at play.api.libs.json.JsResult$class.fold(JsResult.scala:73)
	at play.api.libs.json.JsError.fold(JsResult.scala:13)
	at play.api.libs.json.JsReadable$class.as(JsReadable.scala:21)
```

**Comment by lmenezes** [comment]
@blalor it seems that your cluster doesn't really agree on which nodes are part of it or holds data. For a cluster in this situation, I'm not really sure what could/should be displayed.

Could you get the output of:
/_cluster/state/master_node,routing_table,routing_nodes,blocks
/_nodes/stats/jvm,fs,os,process?human=true
/_stats/docs,store
?
