### ISSUE TITLE
Connect to ES behind nginx

### ISSUE THREAD

**Issue by cp2587** [lmenezes/cerebro#172]
Hello,

Thank you very much for this fantastic tool. 
I am trying to setup cerebro to communicate with an ES instance that sits behind a nginx reverse proxy protected by simple http authentication. 
In application.conf, i have added the following lines:
```
{host = "https://ngninx_server_name", name = "test", auth = { username = "user", password = "password" }
```
But without sucess, i always get the following error:

```
! @74gia1dgk - Internal server error, for (POST) [/navbar] ->
 
play.api.UnexpectedException: Unexpected exception[ConnectException: https://xxxxx:443]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: java.net.ConnectException: https://nginx_server_name:443
	at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:160)
	at org.asynchttpclient.netty.channel.NettyConnectListener$1.onFailure(NettyConnectListener.java:131)
	at org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:26)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
Caused by: java.nio.channels.ClosedChannelException: null
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
[error] application - 

```

**Comment by tarinidash** [comment]
you need to configure truststore to access cerebro over https. Add below to your application.conf

play.ws.ssl {
  trustManager = {
    stores = [
      { type = "JKS", path = "path to .jks file" }
    ]
  }
  loose = {
    acceptAnyCertificate = true // if your cert common name does not match to ngninx_server_name
    }
}

**Comment by svanschalkwyk** [comment]
Thanks!
