### ISSUE TITLE
sqlite using /tmp in centos 7 which is set noexec

### ISSUE THREAD

**Issue by ed0724** [lmenezes/cerebro#180]
Cerebro Ver 0.6.5
Elasticsearch Ver 5.5.0-1

Centos 7 3.10.0-327.36.1.el7.x86_64

The default for /tmp is noexec.  Rather than changing the mount permissions, How can I make sqlite use an alternate temp directory when starting cerebro ?
I see this was talked about in issue 121.  However its frowned up in company env to circumvent the /tmp noexec setting.  Is there a a work around.  Thanks

**Comment by mindscratch** [comment]
Try this:

`JAVA_OPTS=-Djava.io.tmpdir=/path/to/some/other/tmpdir bin/cerebro`

**Comment by lmenezes** [comment]
@ed0724 did you manage to get this to work?

**Comment by ed0724** [comment]
No, gave up and found another solution.  Is there a fix ?

**Comment by lmenezes** [comment]
@ed0724 I haven't tried that, but according to sqlite docs:

```
5. Temporary File Storage Locations

The directory or folder in which temporary files are created is determined by the OS-specific VFS.

On unix-like systems, directories are searched in the following order:

The directory set by PRAGMA temp_store_directory or by the sqlite3_temp_directory global variable
The SQLITE_TMPDIR environment variable
The TMPDIR environment variable
/var/tmp
/usr/tmp
/tmp
The current working directory (".")
The first of the above that is found to exist and have the write and execute bits set is used. The final "." fallback is important for some applications that use SQLite inside of chroot jails that do not have the standard temporary file locations available.
```

would you give this a go and see if it works?

**Comment by ed0724** [comment]
Nm,  I had to make /tmp exec.  Cant leave like that.  Still looking.

**Comment by ed0724** [comment]
the JAVA_OPTS line works, but where would I add that configuration for systemd or init.d startup script

**Comment by 123dev** [comment]
Hi,

I upgraded to 0.7.2 and can no longer start cerebro

I'm getting
`Oops, cannot start the server.
java.sql.SQLTimeoutException: Timeout after 1028ms of waiting for a connection.
        at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227)
        at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:12)
        at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:57)
        at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:60)
        at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:124)
        at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:102)
        at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:117)
        at play.api.db.evolutions.DefaultEvolutionsApi.scripts(EvolutionsApi.scala:82)
        at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:53)
        at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:99)
        at play.api.db.evolutions.ApplicationEvolutions.play$api$db$evolutions$ApplicationEvolutions$$runEvolutions(ApplicationEvolutions.scala:49)
        at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
        at play.api.db.evolutions.ApplicationEvolutions$$anonfun$start$1.apply(ApplicationEvolutions.scala:42)
        at scala.collection.immutable.Stream.foreach(Stream.scala:594)
        at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:42)
        at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:150)
        at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:53)
        at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:53)
        at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:44)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
        at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:145)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205)
        at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
        at com.google.inject.Guice.createInjector(Guice.java:96)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:181)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:123)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:47)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:22)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
`

I tried the setting above but couldn't get it to work.
Please advise.

OS: Linux Debian jessie/sid ( 3.13.0-135-generic x86_64)

Thanks

**Comment by ed0724** [comment]
concerning the JAVA_OPT issue, I used /etc/sysconfig/cerebro with the JAVA_OPTS line and ref'd it in systemd startup.  Working now !!

**Comment by 123dev** [comment]
Thanks,

I can't even start it from command line, let alone as a service.

Typically  I would start it like this.
`bin/cerebro`

Which is now giving me the error above.
I tried

`bin/cerebro -Djava.io.tmpdir=/home/ubuntu/cerebro/tmp`
tmp is pre-created with 777 mod

I've also tried.
`JAVA_OPTS=-Djava.io.tmpdir=/home/ubuntu/cerebro/tmp
export JAVA_OPTS
bin/cerebro`

as well as
`JAVA_OPTS=-Djava.io.tmpdir=/home/ubuntu/cerebro/tmp bin/cerebro`

Always the same error.

Thanks

**Comment by 123dev** [comment]
Update:

Upgarded Ubuntu to 16.04
Linux Debian stretch/sid ( 4.4.0-101-generic x86_64)

And the problem disappeared.
No need to use `Linux Debian stretch/sid ( 4.4.0-101-generic x86_64)`

Thanks

**Comment by moliware** [comment]
I close this ticket as issue seems resolved
