### ISSUE TITLE
SQLTimeoutException when starting cerebro

### ISSUE THREAD

**Issue by gempir** [lmenezes/cerebro#207]
I'm running cerebro as root under /opt/cerebro with all the files that come in the latest release (0.6.7) with openjdk version "1.8.0_141"

But I can't get it to start. 

After a few seconds of starting the binary the following error comes:
```
Oops, cannot start the server.
java.sql.SQLTimeoutException: Timeout after 1001ms of waiting for a connection.
```

with a long Stacktrace and late this:
`
Caused by: java.sql.SQLException: Error opening connection`

and this:

`Caused by: java.lang.Exception: No native library is found for os.name=Linux and os.arch=aarch64. path=/org/sqlite/native/Linux/aarch64`

**Comment by lmenezes** [comment]
this seems to be an issue with the sqlite library: https://github.com/xerial/sqlite-jdbc/issues/106

It seems this has already been fixed, so I will update to the newest version and hopefully this will work out on the next release(will try to have it soon, perhaps tomorrow)

**Comment by gempir** [comment]
Are you sure it's related? I'm running on Debian Stretch Btw.

**Comment by lmenezes** [comment]
well, I didn't explain myself properly or linked to the correct page :)

Your issue isnt *exactly* the same, but it was still about missing the native libraries for aarch64(which were added in the latest release). 

I'm preparing a release now, just let me know if this works then.

**Comment by gbrian** [comment]
Any news on this? Downloaded latest version for Windows. Still having same error:

```
java.sql.SQLTimeoutException: Timeout after 1001ms of waiting for a connection.
        at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227)
        at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93)
        at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:12)
        at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:57)
        at play.api.db.slick.evolutions.internal.DBApiAdapter$DatabaseAdapter.getConnection(DBApiAdapter.scala:60)
        at play.api.db.evolutions.DatabaseEvolutions.databaseEvolutions(EvolutionsApi.scala:124)
        at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:102)
        at play.api.db.evolutions.DatabaseEvolutions.scripts(EvolutionsApi.scala:117)
        at play.api.db.evolutions.DefaultEvolutionsApi.scripts(EvolutionsApi.scala:82)
        at play.api.db.evolutions.ApplicationEvolutions$$anonfun$play$api$db$evolutions$ApplicationEvolutions$$runEvolutions$1.apply$mcV$sp(ApplicationEvolutions.scala:53)
        at play.api.db.evolutions.ApplicationEvolutions.withLock(ApplicationEvolutions.scala:99)
        at play.api.db.evolutions.ApplicationEvolutions.play$api$db$evolutions$ApplicationEvolutions$$runEvolutions(ApplicationEvolutions.scala:49)
```
