### ISSUE TITLE
with 0.7.0 error connect to es 5.4.3 with 0.6.6 can connect

### ISSUE THREAD

**Issue by zqc0512** [lmenezes/cerebro#216]
2017-10-16 10:54:22,205 - [ERROR] - from application in ForkJoinPool-2-worker-27 
Error processing request [path: /overview, body: {"host":"http://xx.xx.xx.xx:9200","username":"","password":""}]
`java.lang.NumberFormatException: For input string: "3655476062"`
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:583)
        at java.lang.Integer.parseInt(Integer.java:615)
        at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:273)
        at scala.collection.immutable.StringOps.toInt(StringOps.scala:29)
        at services.overview.ClusterOverview$$anonfun$12$$anonfun$apply$8.apply(ClusterOverview.scala:67)
        at services.overview.ClusterOverview$$anonfun$12$$anonfun$apply$8.apply(ClusterOverview.scala:67)
        at scala.Option.map(Option.scala:146)
        at services.overview.ClusterOverview$$anonfun$12.apply(ClusterOverview.scala:67)
        at services.overview.ClusterOverview$$anonfun$12.apply(ClusterOverview.scala:64)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at services.overview.ClusterOverview$.apply(ClusterOverview.scala:64)
        at services.overview.DataService$$anonfun$getOverviewData$2.apply(DataService.scala:50)
        at services.overview.DataService$$anonfun$getOverviewData$2.apply(DataService.scala:44)
        at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
        at scala.util.Try$.apply(Try.scala:192)
        at scala.util.Success.map(Try.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by zqc0512** [comment]
with this to a small cluster can connect..
but a lagre cluster can't connect ..
where to change the configure..

**Comment by zqc0512** [comment]
with 0.7.0 error connect to es 5.4.3 with 0.6.6 can connect ,but it slow with 0.6.6

**Comment by lmenezes** [comment]
@zqc0512 some of the changes introduced in 0.7.0 will be rolled back, I hope to come up with a new release soon that both fixes this issue and also improves further performance on large clusters.

**Comment by zqc0512** [comment]
@lmenezes  
thanks. i will test as soon as i can.

**Comment by lmenezes** [comment]
this should now be fixed on 0.7.1. Let me know if its not the case. Thanks for reporting! 👍

**Comment by zqc0512** [comment]
0.7.1 can connect to elasticsearch 5.4.3 ,but allso slow when large cluster  300+indices .thanks.
@lmenezes
