### ISSUE TITLE
BUG LDAP authentication not suited for linux LDAP (only AD)

### ISSUE THREAD

**Issue by RogierSchuring** [lmenezes/cerebro#230]
I'm trying to use cerebro with our corporate LDAP. unfortunately it looks like you only implemented this to work with an AD LDAP.

Code you have in cerebro/app/controllers/auth/ldap/LDAPAuthService.scala:
```
    if (username.endsWith(s"@${config.domain}")) {
      env.put(Context.SECURITY_PRINCIPAL, username)
    } else {
      env.put(Context.SECURITY_PRINCIPAL, s"$username@${config.domain}")
    }
```
According to https://docs.oracle.com/javase/jndi/tutorial/ldap/security/ldap.html this should be something like:
```
env.put(Context.INITIAL_CONTEXT_FACTORY, 
    "com.sun.jndi.ldap.LdapCtxFactory");
env.put(Context.PROVIDER_URL, "ldap://localhost:389/o=JNDITutorial");

// Authenticate as S. User and password "mysecret"
env.put(Context.SECURITY_AUTHENTICATION, "simple");
env.put(Context.SECURITY_PRINCIPAL, "uid=S. User, ou=NewHires, o=JNDITutorial");
env.put(Context.SECURITY_CREDENTIALS, "mysecret");
```
The problem seems with the PRINCIPAL part. I am getting "[LDAP: error code 34 - Invalid DN]" errors when trying to login.

Could you look into this?
If you need more info, let me know.

Complete error:
```
2017-11-19 18:52:29,860 - [ERROR] - from controllers.auth.ldap.LDAPAuthService in application-akka.actor.default-dispatcher-6
login of USERNAME failed
javax.naming.InvalidNameException: [LDAP: error code 34 - Invalid DN]
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:3095)
        at com.sun.jndi.ldap.LdapCtx.processReturnCode(LdapCtx.java:2886)
        at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2800)
        at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
        at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
        at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
        at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
        at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
        at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
        at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
        at javax.naming.InitialContext.init(InitialContext.java:244)
        at javax.naming.InitialContext.<init>(InitialContext.java:216)
        at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
        at controllers.auth.ldap.LDAPAuthService.auth(LDAPAuthService.scala:32)
        at controllers.auth.AuthenticationModuleImpl.authentication(AuthenticationModule.scala:31)
        at controllers.AuthController$$anonfun$login$1$$anonfun$apply$4.apply(AuthController.scala:41)
        at controllers.AuthController$$anonfun$login$1$$anonfun$apply$4.apply(AuthController.scala:40)
        at play.api.data.Form.fold(Form.scala:139)
        at controllers.AuthController$$anonfun$login$1.apply(AuthController.scala:35)
        at controllers.AuthController$$anonfun$login$1.apply(AuthController.scala:34)
        at play.api.mvc.ActionBuilder$$anonfun$apply$13.apply(Action.scala:371)
        at play.api.mvc.ActionBuilder$$anonfun$apply$13.apply(Action.scala:370)
        at play.api.mvc.Action$.invokeBlock(Action.scala:498)
        at play.api.mvc.Action$.invokeBlock(Action.scala:495)
        at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
        at scala.Option.map(Option.scala:146)
        at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
        at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:415)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
Config part in application.conf:
```
auth = {
  type: ldap
    settings: {
      url = "ldaps://test.ldap.server"
      base-dn = "ou=employee, o=company"
      method  = "simple"
      user-domain = ""
    }
}
```

p.s. I am fairly new to LDAP so it is entirely possible that I'm doing it wrong.

**Comment by FR-TheS** [comment]
What is the user put for login?
The base-dn is correct?
Put the port in the ldap url to be sure to use the SSL port.

**Comment by tlied2** [comment]
@FR-TheS The problem I saw, and believe that @RogierSchuring is seeing, is that email-style usernames are coded into the LDAP auth implementation, but our LDAP servers expect a different format of username which doesn't resemble an email address. My PR #242 attempts to allow more flexible username formatting, which is sufficient to allow me to successfully bind against my OpenLDAP servers.

**Comment by RogierSchuring** [comment]
> @FR-TheS The problem I saw, and believe that @RogierSchuring is seeing, is that email-style usernames are coded into the LDAP auth implementation, but our LDAP servers expect a different format of username which doesn't resemble an email address. My PR #242 attempts to allow more flexible username formatting, which is sufficient to allow me to successfully bind against my OpenLDAP servers.

That's the problem indeed!
our users login with their user key like "kyle"
Our LDAP expects that in the search term. Not the hardcoded '@' that is attached to the username.
If that is only added when "user-domain" is filled in, than I think it should work for our use case.

**Comment by moliware** [comment]
@RogierSchuring After merging #246 it should be fixed. Could you let us know if the problem persists?

**Comment by RogierSchuring** [comment]
@moliware Sorry for the late reply (holiday)
Testing now, and it looks promising.
Only can't get the ssl handshake working...

@tlied2 Could you give me a hand in configuring the needed ssl stuff?
Our LDAP uses ldaps to connect to.

Our relevant application.conf settings:
`auth = {
  type: ldap
    settings: {
      url = "ldaps://test.ldap.intranet:636"
      base-dn = "ou=people,o=ourcompany"
      method  = "simple"
      user-format = "uid=%s,%s"
      user-domain = ""
    }
}`
including the correct truststore:
`play.ws.ssl {
  trustManager = {
    stores = [
      { type = "JKS", path = "/etc/cerebro/certificates/ca.jks" }
    ]
  }
  enabledProtocols = [
    "TLSv1.2"
  ]
  enabledCipherSuites = [
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA _WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
    "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384"
  ]
}
`
The enabledProtocols and enabledCipherSuites settings are not taken into account. so maybe i'm doing this wrong?

error when trying to login:
`2018-06-29 14:06:00,115 - [ERROR] - from controllers.auth.ldap.LDAPAuthService in application-akka.actor.default-dispatcher-4 - login of user failed - javax.naming.CommunicationException: simple bind failed: test.ldap.intranet:636
        at com.sun.jndi.ldap.LdapClient.authenticate(LdapClient.java:219)
        at com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2791)
        at com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
        at com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
        at com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
        at com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
        at com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
        at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:684)
        at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313)
        at javax.naming.InitialContext.init(InitialContext.java:244)
        at javax.naming.InitialContext.<init>(InitialContext.java:216)
        at javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:101)
        at controllers.auth.ldap.LDAPAuthService.auth(LDAPAuthService.scala:36)
        at controllers.auth.AuthenticationModuleImpl.authentication(AuthenticationModule.scala:31)
        at controllers.AuthController$$anonfun$login$1$$anonfun$apply$4.apply(AuthController.scala:47)
        at controllers.AuthController$$anonfun$login$1$$anonfun$apply$4.apply(AuthController.scala:46)
        at play.api.data.Form.fold(Form.scala:146)
        at controllers.AuthController$$anonfun$login$1.apply(AuthController.scala:41)
        at controllers.AuthController$$anonfun$login$1.apply(AuthController.scala:40)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:482)
        at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:480)
        at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:419)
        at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:96)
        at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:89)
        at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2$$anonfun$1.apply(Accumulator.scala:174)
        at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2$$anonfun$1.apply(Accumulator.scala:174)
        at scala.util.Try$.apply(Try.scala:192)
        at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2.apply(Accumulator.scala:174)
        at play.api.libs.streams.StrictAccumulator$$anonfun$mapFuture$2.apply(Accumulator.scala:170)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
        at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:211)
        at play.core.server.AkkaHttpServer.executeAction(AkkaHttpServer.scala:298)
        at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:254)
        at play.core.server.AkkaHttpServer.play$core$server$AkkaHttpServer$$handleRequest(AkkaHttpServer.scala:195)
        at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:106)
        at play.core.server.AkkaHttpServer$$anonfun$5.apply(AkkaHttpServer.scala:106)
        at akka.stream.impl.fusing.MapAsync$$anon$25.onPush(Ops.scala:1194)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
        at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent$class.execute(ActorGraphInterpreter.scala:44)
        at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:77)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
        at akka.actor.ActorCell.invoke(ActorCell.scala:559)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:938)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at com.sun.jndi.ldap.Connection.run(Connection.java:860)
        at java.lang.Thread.run(Thread.java:748)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
        at sun.security.validator.Validator.validate(Validator.java:260)
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
        ... 12 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
        ... 18 common frames omitted
`

**Comment by RogierSchuring** [comment]
a colleague of mine got it working with the following startup option:
-Djavax.net.ssl.trustStore=location-to-ca.jks
Working fine now!
