### ISSUE TITLE
Error while editing large index template

### ISSUE THREAD

**Issue by Cova** [lmenezes/cerebro#262]
While making a change to a large index template, when I try and save it I get an error.  Checking in application.log - it seems to be caused by this:

io.netty.handler.codec.TooLongFrameException: HTTP header is larger than 8192 bytes.

Is this a setting I could increase somewhere in application.conf?

**Comment by lmenezes** [comment]
HTTP header?? Hum, that I would not have expected. 

Could you share the index template(modifying whatever is necessary for privacy reasons) in a way that you can still reproduce the error through cerebro?

**Comment by lmenezes** [comment]
@Cova is this still an issue?

**Comment by jhlovesky** [comment]
```
{
  "order": 0,
  "template": "test-*",
  "settings": {
    "index": {
      "number_of_shards": "2",
      "number_of_replicas": "0"
    }
  },
  "mappings": {
    "_default_": {
      "_source": {
        "enabled": true
      },
      "dynamic": "false",
      "dynamic_templates": [
        {
          "strings": {
            "mapping": {
              "ignore_above": 256,
              "index": "not_analyzed",
              "type": "{dynamic_type}",
              "doc_values": true
            },
            "match_mapping_type": "string"
          }
        },
        {
          "doc_values": {
            "mapping": {
              "type": "{dynamic_type}",
              "doc_values": true
            },
            "match_mapping_type": "*"
          }
        }
      ],
      "_all": {
        "enabled": false
      },
      "properties": {
        "role": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "activity": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "activity_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "open_id": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "clone_app": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "cnzz": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "attributively": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "pro_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "phone": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "target_type": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "target_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "relation_type": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "operator": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "relation_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "candy": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "candy_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "channel": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "type": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "platform": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "points": {
          "type": "double",
          "doc_values": true
        },
        "vid": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "uid": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "zone": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "zone_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "sub_type": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "@version": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "term": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "currency": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "metric_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "trade_no_join": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "currency_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "net": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "cash": {
          "type": "double",
          "doc_values": true
        },
        "order": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "order_no": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "share_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "total_fee": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "news": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "news_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "trace_time": {
          "format": "epoch_millis",
          "type": "date",
          "doc_values": true
        },
        "headers": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "http_user_agent": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "product": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "product_type": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "product_no": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "ver": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "trace_id": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "query_condition": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "geoip": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "city_name": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "ip": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "country_name": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "location": {
              "type": "geo_point",
              "doc_values": true
            },
            "real_region_name": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "idfa": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "base_info": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "motion": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "phone": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "message": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "sub_type": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "item_type": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "length": {
              "type": "integer",
              "doc_values": true
            },
            "type": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "keyword": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "std_keyword": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "to_platform": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "from_uid": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "article": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "article_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "flag_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "utm": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "campaign": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "term": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "source": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "medium": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            },
            "content": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        },
        "product_line": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "referrer": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "@timestamp": {
          "format": "dateOptionalTime",
          "type": "date",
          "doc_values": true
        },
        "shop_uid": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "to_uid": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "imei": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "page_code": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "position": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "device": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "status": {
          "index": "not_analyzed",
          "type": "string",
          "doc_values": true
        },
        "promotion": {
          "dynamic": "false",
          "type": "object",
          "properties": {
            "material_id": {
              "index": "not_analyzed",
              "type": "string",
              "doc_values": true
            }
          }
        }
      }
    }
  },
  "aliases": {}
}
```

the index template! create new template happed exception。

version: cerebro-0.8.1

```
play.shaded.ahc.io.netty.handler.codec.TooLongFrameException: HTTP header is larger than 8192 bytes.
	at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.newException(HttpObjectDecoder.java:827)
	at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.process(HttpObjectDecoder.java:819)
	at play.shaded.ahc.io.netty.buffer.AbstractByteBuf.forEachByteAsc0(AbstractByteBuf.java:1023)
	at play.shaded.ahc.io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1003)
	at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(HttpObjectDecoder.java:791)

```

**Comment by jhlovesky** [comment]
How Can I Set The Http Header Size ? @lmenezes

**Comment by Fil0sOFF** [comment]
Got a similar issue myself. Adding `-Dplay.shaded.ahc.org.asynchttpclient.httpClientCodecMaxHeaderSize=32768` to launch options solved the issue.
