### ISSUE TITLE
NPE when connecting to "localhost:9200" instead of "http://localhost:9200"

### ISSUE THREAD

**Issue by mo** [lmenezes/cerebro#274]
1. launch cerebro
2. in the node address field enter "localhost:9200"
3. click "connect"

actual:
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
[error] application - 

! @777k71hmn - Internal server error, for (POST) [/connect] ->
 
play.api.UnexpectedException: Unexpected exception[NullPointerException: host]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: java.lang.NullPointerException: host
	at org.asynchttpclient.util.Assertions.assertNotNull(Assertions.java:23)
	at org.asynchttpclient.uri.Uri.<init>(Uri.java:65)
	at org.asynchttpclient.uri.Uri.create(Uri.java:38)
	at org.asynchttpclient.uri.Uri.create(Uri.java:31)
	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:148)

**Comment by thibault-ketterer** [comment]
just lost 10 minutes on this, error could be more clear..
