### ISSUE TITLE
didn't support https?

### ISSUE THREAD

**Issue by taowu82** [lmenezes/cerebro#276]
Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1728)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:330)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:992)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:989)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1467)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1120)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1005)
	... 18 common frames omitted

hosts = [
  {
    host = "https://localhost:9200"
    name = "es_nginx"
    auth = {
      username = "elastic"
      password = "passwd"
    }
  }
]

**Comment by tlied2** [comment]
I'm successfully using HTTPS with cerebro (I'm trying out SearchGuard). I have a real cert signed by a commonly trusted CA, so I didn't have to do anything special on the cerebro side, just switched it to https in the host field in the config. Java SSL error messages are particularly unhelpful, but being that you are using "localhost", I would assume you are using a self-signed cert, or something to that effect, which will not be trusted by the nodejs built-in CAs (and if you aren't, you need to be using a hostname that matches the cert, which won't be localhost). If you are using a self-signed cert or a self-signed CA to generate certs, you likely need to have a look at https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file or setting one of the other nodejs TLS options to meet your needs.

**Comment by lmenezes** [comment]
thanks @tlied2 for the extra info :)

**Comment by zqc0512** [comment]
like this
`keytool -import -trustcacerts -keystore /usr/java/jdk1.8.0_xxxx/jre/lib/security/cacerts  -storepass changeit -noprompt -alias xxx -file /root/xxx.cer `
import the cert into jdk.

**Comment by pgovalkar** [comment]
thank you
