### ISSUE TITLE
unable to start docker-cerebro with minishift...oops cannot start server

### ISSUE THREAD

**Issue by mkleint-magari** [lmenezes/cerebro#372]
i have a local minishift cluster and want to deploy cerebro within it. but doesnt work. i am running the cerebro-container with the following config:

`# Secret will be used to sign session cookies, CSRF tokens and for other encryption utilities.
# It is highly recommended to change this value before running cerebro in production.
secret = "ki:s:[[@=Ag?QI`W2jMwkY:eqvrJ]JqoJyi2axj3ZvOv^/KavOT4ViJSv?6YY4[N"

# Application base path
basePath = "/"

# Defaults to RUNNING_PID at the root directory of the app.
# To avoid creating a PID file set this value to /dev/null
#pidfile.path = "/var/run/cerebro.pid"
pidfile.path=/dev/null

# Rest request history max size per user
# rest.history.size = 50 // defaults to 50 if not specified

# Path of local database file
#data.path: "/var/lib/cerebro/cerebro.db"
data.path = "./cerebro.db"

es = {
  gzip = true
}

# Authentication
auth = {
}

# A list of known hosts
hosts = [
  {
    host = "http://daparto-search-cluster-node-1:9200"
    name = "daparto-search-cluster-node-1:9200"
  },
  {
    host = "http://daparto-search-cluster-node-2:9200"
    name = "daparto-search-cluster-node-2:9200"
  },
  {
    host = "http://daparto-pinc-elasticsearch-node-1:9200"
    name = "daparto-pinc-elasticsearch-node-1:9200"
  },
  {
    host = "http://daparto-pinc-elasticsearch-node-2:9200"
    name = "daparto-pinc-elasticsearch-node-2:9200"
  },
  # Example of host with authentication
  #{
  #  host = "http://some-authenticated-host:9200"
  #  name = "Secured Cluster"
  #  auth = {
  #    username = "username"
  #    password = "secret-password"
  #  }
  #}
]`

WARNING: An illegal reflective access operation has occurred
--
  | WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/opt/cerebro/lib/com.google.inject.guice-4.2.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
  | WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
  | WARNING: All illegal access operations will be denied in a future release
  | Oops, cannot start the server.
  | com.google.inject.CreationException: Unable to create injector, see the following errors:
  | 1) No implementation for play.api.db.slick.DatabaseConfigProvider was bound.
  | while locating play.api.db.slick.DatabaseConfigProvider
  | for the 1st parameter of dao.RestHistoryDAOImpl.<init>(RestHistoryDAO.scala:29)
  | at dao.RestHistoryDAO.class(RestHistoryDAO.scala:1)
  | while locating dao.RestHistoryDAO
  | for the 4th parameter of controllers.RestController.<init>(RestController.scala:18)
  | while locating controllers.RestController
  | for the 4th parameter of router.Routes.<init>(Routes.scala:97)
  | at play.api.inject.RoutesProvider$.bindingsFromConfiguration(BuiltinModule.scala:123):
  | Binding(class router.Routes to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)
  | 1 error
  | at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
  | at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:159)
  | at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
  | at com.google.inject.Guice.createInjector(Guice.java:87)
  | at com.google.inject.Guice.createInjector(Guice.java:78)
  | at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:186)
  | at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:139)
  | at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
  | at play.core.server.ProdServerStart$.start(ProdServerStart.scala:57)
  | at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
  | at play.core.server.ProdServerStart.main(ProdServerStart.scala)

**Comment by mkleint-magari** [comment]
i found the solution. the configuration file is somehow incomplete. 
when i use the following configuration. the pod comes up fine and everything is working.


```
secret = "ki:s:[[@=Ag?QI`W2jMwkY:eqvrJ]JqoJyi2axj3ZvOv^/KavOT4ViJSv?6YY4[N"
play.http.secret.key = ${secret}

pidfile.path=/dev/null

es {
  gzip = false
}
play.ws.compressionEnabled = ${es.gzip}

# The application languages
play.i18n.langs = ["en"]

# The application base path
basePath = "/"
play.http.context = ${basePath}

# Database configuration
data.path = "./cerebro.db"
slick.dbs.default.driver = "slick.driver.SQLiteDriver$"
slick.dbs.default.db.driver = org.sqlite.JDBC
slick.dbs.default.db.url = "jdbc:sqlite:"${data.path}
play.evolutions.db.default.autoApply = true
```

**Comment by ftoledo-rb** [comment]
this config solve my issue, thanks for the idea!
```

# Secret will be used to sign session cookies, CSRF tokens and for other encryption utilities.
# It is highly recommended to change this value before running cerebro in production.
secret = "ki:s:[[@=Ag?QI`W2jMwkY:eqvrJ]<RANDOM>"
play.http.secret.key = ${secret}

# Application base path
basePath = "/"

# Defaults to RUNNING_PID at the root directory of the app.
# To avoid creating a PID file set this value to /dev/null
#pidfile.path = "/var/run/cerebro.pid"
pidfile.path=/dev/null

# Rest request history max size per user
rest.history.size = 50 // defaults to 50 if not specified

# Path of local database file
#data.path: "/var/lib/cerebro/cerebro.db"
data.path = "./cerebro.db"
slick.dbs.default.driver = "slick.driver.SQLiteDriver$"
slick.dbs.default.db.driver = org.sqlite.JDBC
slick.dbs.default.db.url = "jdbc:sqlite:"${data.path}
play.evolutions.db.default.autoApply = true

play {
  # Cerebro port, by default it's 9000 (play's default)
  server.http.port = ${?CEREBRO_PORT}
}

es = {
  gzip = true
}

# A list of known hosts
hosts = [
  {
    host = ${?ELASTIC_URL}
    name = ${?ENVIRONMENT}
    headers-whitelist = [ "x-proxy-user", "x-proxy-roles", "X-Forwarded-For" ]
  }
]

```
