### ISSUE TITLE
How to access to ES 7.x with X-Pack

### ISSUE THREAD

**Issue by hurvajs77** [lmenezes/cerebro#389]
Hi,
I use Elasticsearch 7.1 with basic version of X-Pack, so I need authorise before login to Elastic. But Cerebo has only node URL, nothing more.

I use your Dockerfile.

Thanks, Jiří

**Comment by hurvajs77** [comment]
there is a log from docker container...
```
[error] application -

! @7cmchh0g1 - Internal server error, for (POST) [/connect] ->

play.api.UnexpectedException: Unexpected exception[ConnectException: Connection refused: localhost/127.0.0.1:9200]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:319)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:243)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:382)
	at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:380)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:9200
	at play.shaded.ahc.org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at play.shaded.ahc.org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at play.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at play.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
Caused by: play.shaded.ahc.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:9200
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at play.shaded.ahc.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at play.shaded.ahc.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at play.shaded.ahc.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at play.shaded.ahc.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
```

**Comment by servergeeks** [comment]
What kind of auth do you have on your es cluster?

**Comment by Theoooooo** [comment]
If you are using the free user authentication available from the 7.x version,which i'm using as well,  
there is an exemple in the configuration file.
As if you use certificate and TLS, i assume it's not surpported. There no line what so ever in the documentation about that

**Comment by hurvajs77** [comment]
Yes, it's true - I tried connect to Elastic out of Docker compose, so it's my fault. If add Cerebro into Docker, works correctly. Thanks for answers :-)
