### ISSUE TITLE
Cerebro 0.8.4 fails on Java8 due to Java11 classes

### ISSUE THREAD

**Issue by k-c-p** [lmenezes/cerebro#393]
I use Cerebro on Java8. When trying out version 0.8.4 is starts without any complaint but when accessed it throughs an error complaining about the Java version.
```
play.api.UnexpectedException: Unexpected exception[RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:319)
at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:243)
at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:382)
at play.core.server.AkkaHttpServer$$anonfun$1.applyOrElse(AkkaHttpServer.scala:380)
at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
Caused by: java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: controllers/routes
at play.api.mvc.ActionBuilder$$anon$10.apply(Action.scala:425)
at play.api.mvc.Action.$anonfun$apply$2(Action.scala:97)
at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
Caused by: java.lang.UnsupportedClassVersionError: controllers/routes
at controllers.auth.AuthAction.$anonfun$invokeBlock$2(AuthAction.scala:22)
at scala.Option.getOrElse(Option.scala:138)
at controllers.auth.AuthAction.invokeBlock(AuthAction.scala:20)
at controllers.auth.AuthAction.invokeBlock(AuthAction.scala:12)
at play.api.mvc.ActionBuilder$$anon$10.apply(Action.scala:420)
```

Digging through the jars I found that two classes in`cerebro.cerebro-0.8.4-sans-externalized.jar` are compiled with Java11:
```
[charly@montreal unpack]$ jar xf /tmp/cerebro-0.8.4/lib/cerebro.cerebro-0.8.4-sans-externalized.jar 
[charly@montreal unpack]$ find . -name '*.class' | xargs file | grep "55.0"
./controllers/routes$javascript.class:                                       compiled Java class data, version 55.0
./controllers/routes.class:                                                  compiled Java class data, version 55.0
```

Any particular reason for that? All other classes have the Java 8 class version (0.52). In Cerebro 0.8.3 these classes are compiled with Java8 too.

Thanks in advance for looking into this.

**Comment by zhou-mfk** [comment]
I use openjdk-11 and it works fine！！！

**Comment by lmenezes** [comment]
@k-c-p Sorry this took a long time until I finally have a look. You were right, I assume it was accidentally compiled with for jdk11, and would not work with jdk8. 

As a note, the latest version requires jdk11 :)
