### ISSUE TITLE
_cat url in REST?

### ISSUE THREAD

**Issue by scippio** [lmenezes/cerebro#41]
I'm trying call '_cat/health' (GET) via REST console and this return me:
```
"

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Error</title>
        <link rel="shortcut icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAlFJREFUeNqUU8tOFEEUPVVdNV3dPe8xYRBnjGhmBgKjKzCIiQvBoIaNbly5Z+PSv3Aj7DSiP2B0rwkLGVdGgxITSCRIJGSMEQWZR3eVt5sEFBgTb/dN1yvnnHtPNTPG4PqdHgCMXnPRSZrpSuH8vUJu4DE4rYHDGAZDX62BZttHqTiIayM3gGiXQsgYLEvATaqxU+dy1U13YXapXptpNHY8iwn8KyIAzm1KBdtRZWErpI5lEWTXp5Z/vHpZ3/wyKKwYGGOdAYwR0EZwoezTYApBEIObyELl/aE1/83cp40Pt5mxqCKrE4Ck+mVWKKcI5tA8BLEhRBKJLjez6a7MLq7XZtp+yyOawwCBtkiBVZDKzRk4NN7NQBMYPHiZDFhXY+p9ff7F961vVcnl4R5I2ykJ5XFN7Ab7Gc61VoipNBKF+PDyztu5lfrSLT/wIwCxq0CAGtXHZTzqR2jtwQiXONma6hHpj9sLT7YaPxfTXuZdBGA02Wi7FS48YiTfj+i2NhqtdhP5RC8mh2/Op7y0v6eAcWVLFT8D7kWX5S9mepp+C450MV6aWL1cGnvkxbwHtLW2B9AOkLeUd9KEDuh9fl/7CEj7YH5g+3r/lWfF9In7tPz6T4IIwBJOr1SJyIGQMZQbsh5P9uBq5VJtqHh2mo49pdw5WFoEwKWqWHacaWOjQXWGcifKo6vj5RGS6zykI587XeUIQDqJSmAp+lE4qt19W5P9o8+Lma5DcjsC8JiT607lMVkdqQ0Vyh3lHhmh52tfNy78ajXv0rgYzv8nfwswANuk+7sD/Q0aAAAAAElFTkSuQmCC">
        <style>
            html, body, pre {
                margin: 0;
                padding: 0;
                font-family: Monaco, 'Lucida Console', monospace;
                background: #ECECEC;
            }
            h1 {
                margin: 0;
                background: #A31012;
                padding: 20px 45px;
                color: #fff;
                text-shadow: 1px 1px 1px rgba(0,0,0,.3);
                border-bottom: 1px solid #690000;
                font-size: 28px;
            }
            p#detail {
                margin: 0;
                padding: 15px 45px;
                background: #F5A0A0;
                border-top: 4px solid #D36D6D;
                color: #730000;
                text-shadow: 1px 1px 1px rgba(255,255,255,.3);
                font-size: 14px;
                border-bottom: 1px solid #BA7A7A;
            }
        </style>
    </head>
    <body>
        <h1>Oops, an error occurred</h1>

        <p id="detail">
            This exception has been logged with id <strong>729m36519</strong>.
        </p>

    </body>
</html>
```

In console everything is ok:
```
curl -XGET 'http://localhost:9200/_cat/health'
1480896067 01:01:07 elasticsearch yellow 1 1 5 5 0 0 5 0 - 50.0%
```

Maybe this will be usefull. This is output in elasticsearch after call from cerebro.
```
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
com.fasterxml.jackson.core.JsonParseException: Invalid numeric value: Leading zeroes not allowed
 at [Source: [B@5d0f44fd; line: 1, column: 13]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.base.ParserBase.reportInvalidNumber(ParserBase.java:995) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._verifyNoLeadingZeroes(UTF8StreamJsonParser.java:1469) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parsePosNumber(UTF8StreamJsonParser.java:1315) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
[error] application - 

! @729m49gi7 - Internal server error, for (POST) [/rest/request] ->
 
play.api.UnexpectedException: Unexpected exception[JsonParseException: Invalid numeric value: Leading zeroes not allowed
 at [Source: [B@5d0f44fd; line: 1, column: 13]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid numeric value: Leading zeroes not allowed
 at [Source: [B@5d0f44fd; line: 1, column: 13]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.base.ParserBase.reportInvalidNumber(ParserBase.java:995) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._verifyNoLeadingZeroes(UTF8StreamJsonParser.java:1469) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parsePosNumber(UTF8StreamJsonParser.java:1315) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]

```

**Comment by celesteking** [comment]
Hell, whole /_cat/ API is busted. Not a single one working. I'm getting:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "index_not_found_exception",
        "reason": "no such index",
        "resource.type": "index_expression",
        "resource.id": "",
        "index_uuid": "_na_",
        "index": ""
      }
    ],
    "type": "index_not_found_exception",
    "reason": "no such index",
    "resource.type": "index_expression",
    "resource.id": "",
    "index_uuid": "_na_",
    "index": ""
  },
  "status": 404
}
```

**Comment by lmenezes** [comment]
hey all,

there are 2 reasons this is failing:

@scippio - The REST client expects all responses to be valid json(cat api requests are not). You can force cat api responses to be json by appending a format=json parameter.

@celesteking - You are likely using POST for the _cat requests, and as these are GET only, ES has trouble figuring out which API you are actuallu trying to reach.

I will be soon adding generic _cat section to cerebro, which should work better and also manage the data as a table, which is where the cat api makes most sense.

Hope this helps for now.

**Comment by lmenezes** [comment]
FYI: https://github.com/lmenezes/cerebro/issues/44

**Comment by scippio** [comment]
?format=json helped ... thank you! :+1:
