### ISSUE TITLE
Reverse proxy nginx

### ISSUE THREAD

**Issue by webtrend** [lmenezes/cerebro#459]
I have cerebro installed on one of our servers and it works fine with this url
http://mydomain:9000/
I want to setup a reverse proxy on nginx so that I can load it with this type of url 
http://mydomain/cerebro/

I have setup my nginx config like this
```
        location /cerebro/ {
        proxy_pass http://localhost:9000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
         }
```

However this generates a 404 error from scala ( css styling on the 404 page seems to suggest that it is scala throwing this error). 

In the cerebro application.log, I see error like this

```
2020-06-12 01:02:31,762 - [ERROR] - from akka.io.TcpListener in application-akka.actor.default-dispatcher-5 
Bind failed for TCP channel on endpoint [/0.0.0.0:9000]
java.net.BindException: [/0.0.0.0:9000] Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:455)
        at java.base/sun.nio.ch.Net.bind(Net.java:447)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:59)
        at akka.io.TcpListener.<init>(TcpListener.scala:56)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at akka.util.Reflect$.instantiate(Reflect.scala:69)
        at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:100)
        at akka.actor.Props.newActor(Props.scala:226)
        at akka.actor.ActorCell.newActor(ActorCell.scala:609)
        at akka.actor.ActorCell.create(ActorCell.scala:635)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
Any suggestions?

**Comment by webtrend** [comment]
Just a quick update. The error I quoted above in application.log seem to be occurring regardless of whether I have reverse proxy configured on nginx. This error seems
 to be related to something else.

**Comment by webtrend** [comment]
I found the solution to this problem from one of the earlier posts on this topic. I just needed to change the default base path.
