### ISSUE TITLE
error - cannot invoke the action

### ISSUE THREAD

**Issue by cp2587** [lmenezes/cerebro#49]
Hi,

Thanks for your work on this plugin, it is very much appreciated (i am coming from the kopf project). I am trying to run an instance of cerebro but the application doesn't want to load. It outputs a lot of error of the type
`[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'No': was expecting 'null', 'true', 'false' or NaN
 at [Source: [B@173a62d5; line: 1, column: 4]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3323) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3301) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._matchToken(UTF8StreamJsonParser.java:2622) ~[com.fasterxml.jackson.core.jackson-core-2.5.4.jar:2.5.4]
`

Being myself completely ignorant in java & scala, do you have any idea on how to solve the problem ? My ES cluster seems to work juste fine (i can do a curl https://user:passwd@xxxx//_cat/nodes?v  - note that i use https)

**Comment by lmenezes** [comment]
hey there

when does this error occur? when you startup cerebro? or trying to connect to your node(which is using https)?

**Comment by cp2587** [comment]
Cerebro is starting up correctly and if i try to connect to the localhost node, it works. The problem arises when i try to connect to an https node with user:password...

**Comment by cauepor** [comment]
I'm having the same problem, any heads up about this? I'm using cerebro 0.5 trying to connect to a ES 5 cluster protected by user:password through HTTPS

**Comment by lmenezes** [comment]
could you try the newest version? Even though there was no work directed at solving this, the error messages should tell us more than they did.
