### ISSUE TITLE
Analysis fails on some indices with "List('properties' is undefined on object"

### ISSUE THREAD

**Issue by centic9** [lmenezes/cerebro#506]
Some specific index triggers the following error when trying to use the "analyze" functionality, maybe the "metadata" is responsible here:

```
[error] application - Error processing request [path: /analysis/fields, body: {"index":"idx","host":"env"}]
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(JsonValidationError(List('properties' is undefined on object: {"migrationIds":["CommentTokenToUserId"]}),List())))))
        at play.api.libs.json.JsReadable.$anonfun$as$2(JsReadable.scala:25)
        at play.api.libs.json.JsError.fold(JsResult.scala:66)
        at play.api.libs.json.JsReadable.as(JsReadable.scala:24)
        at play.api.libs.json.JsReadable.as$(JsReadable.scala:23)
        at play.api.libs.json.JsUndefined.as(JsLookup.scala:193)
```

Template:

```
{ - 
  "idx": { - 
    "mappings": { - 
      "_meta": { - 
        "migrationIds": [ - 
          "CommentTokenToUserId"
        ]
      },
      "_all": { - 
        "enabled": false
      },
      "dynamic_templates": [ - 
        { - 
          "string_fields": { - 
            "match": "*",
            "match_mapping_type": "string",
            "mapping": { - 
              "norms": "false",
              "type": "keyword"
            }
          }
        }
      ],
      "date_detection": false,
      "properties": { - 
        "commentId": { - 
          "type": "keyword"
        },
        "commentOwnerId": { - 
          "type": "keyword"
        }
...
      }
    }
  }
}
```

**Comment by moliware** [comment]
Hi! Which version of cerebro and elasticsearch are you using?

**Comment by centic9** [comment]
Cerebro 0.9.4
Elasticsearch 7.10.0
