### ISSUE TITLE
500 happens during login localhost elasticsearch cluster

### ISSUE THREAD

**Issue by godlockin** [lmenezes/cerebro#536]
OS: Mac
version: lmenezes/cerebro:0.9.4
steps:
1. pull the cerebro image 'lmenezes/cerebro:0.9.4'
2. pull the elasticsearch image 'elastic/elasticsearch:7.15.0'
3. start the elasticsearch by `docker run -it -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node"  elastic/elasticsearch:7.15.0`
4. check the elasticsearch's status
```bash
 curl http://localhost:9200/_cat/health
1637287202 02:00:02 docker-cluster green 1 1 1 1 0 0 0 0 - 100.0%
```
5.  start the cerebro image by
```bash
docker run --rm -it --name cerebro -p 9000:9000 lmenezes/cerebro
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/opt/cerebro/lib/com.google.inject.guice-4.2.3.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[info] play.api.Play - Application started (Prod) (no global state)
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9000
```
6. login to the cerebro's webpage `http://localhost:9000/#!/connect`
7. but whether `http://localhost:9200` or `http://127.0.0.1:9200` 500 error will happen
```bash
[error] p.a.h.DefaultHttpErrorHandler -

! @7lm2o1oj1 - Internal server error, for (POST) [/connect] ->

play.api.UnexpectedException: Unexpected exception[ConnectException: Connection refused: localhost/127.0.0.1:9200]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:355)
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:261)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:430)
	at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:422)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:454)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:9200
	at play.shaded.ahc.org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
	at play.shaded.ahc.org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
	at play.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
	at play.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
Caused by: play.shaded.ahc.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:9200
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at play.shaded.ahc.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
	at play.shaded.ahc.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
	at play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)
```

so, the question is, maybe some steps i made mistake, but can you tell me what i can do to fix it?

btw, 500 will happen during my login remote elasticsearch cluster as well

**Comment by godlockin** [comment]
typo fix before

i can get access the localhost elasticsearch node by curl, but somehow can't login by cerebro :(

what i need to fix on this case?

```bash
curl http://localhost:9200
{
  "name" : "node1",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "nGFMKy5KQGiyLU1xEMHg5w",
  "version" : {
    "number" : "7.15.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "79d65f6e357953a5b3cbcc5e2c7c21073d89aa29",
    "build_date" : "2021-09-16T03:05:29.143308416Z",
    "build_snapshot" : false,
    "lucene_version" : "8.9.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by rschirin** [comment]
ES container and Cerebro container are using the same network layer?

**Comment by godlockin** [comment]
oh yes, i've tried to bootstrap a cerebro node with es nodes in 1 docker-compose file which makes them belongs to the same network, and it works

**Comment by robertotambunan** [comment]
@godlockin - can you share your docker compose file? I've done the same thing but somehow it doesn't work on my side. The cerebro keep can't connect to the ES
