### ISSUE TITLE
Can't load the ES overview pages with "error": "HTTP header is larger than 8192 bytes."

### ISSUE THREAD

**Issue by xgxshtc** [lmenezes/cerebro#578]
[error] application - Error processing request [path: /overview, body: {"host":"xxxxxx"}]
play.shaded.ahc.io.netty.handler.codec.TooLongFrameException: HTTP header is larger than 8192 bytes.
        at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.newException(HttpObjectDecoder.java:843)
        at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.process(HttpObjectDecoder.java:835)
        at play.shaded.ahc.io.netty.buffer.AbstractByteBuf.forEachByteAsc0(AbstractByteBuf.java:1350)
        at play.shaded.ahc.io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1330)
        at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(HttpObjectDecoder.java:807)
[error] application - Error processing request [path: /cluster_changes, body: {"host":"xxxxxx"}]
play.shaded.ahc.io.netty.handler.codec.TooLongFrameException: HTTP header is larger than 8192 bytes.
        at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.newException(HttpObjectDecoder.java:843)
        at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.process(HttpObjectDecoder.java:835)
        at play.shaded.ahc.io.netty.buffer.AbstractByteBuf.forEachByteAsc0(AbstractByteBuf.java:1350)
        at play.shaded.ahc.io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1330)
        at play.shaded.ahc.io.netty.handler.codec.http.HttpObjectDecoder$HeaderParser.parse(HttpObjectDecoder.java:807)

**Comment by GYFgaoyuefei** [comment]
好的，我已收到

**Comment by thomas-lehmann** [comment]
I had the same issue. Please add -Dplay.server.max-header-size=32k to the cerebro daemon launch command. 
Someting like: 
`bin/cerebro -Dhttp.port=1234 -Dhttp.address=127.0.0.1 -Dplay.server.max-header-size=32k`
