### ISSUE TITLE
cerebro and Elasticsearch 5.x missing authentication token for REST request

### ISSUE THREAD

**Issue by hesmaeili** [lmenezes/cerebro#69]
Hello,
Trying Cerebro with Elasticsearch 2.X is fine. Switching to Elasticsearch 5.X throws the following errors:

```
[warn] application - Logger configuration in conf files is deprecated and has no effect. Use a logback configuration file instead.
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /127.0.0.1:1234
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(List('routing_table' is undefined on object: {"error":{"root_cause":[{"type":"security_exception","reason":"missing
 authentication token for REST request [/_cluster/state/master_node,routing_table,routing_nodes,blocks]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_excepti
on","reason":"missing authentication token for REST request [/_cluster/state/master_node,routing_table,routing_nodes,blocks]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}},"status":401}),WrappedArray())))))
        at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:20) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]
        at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:20) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]
        at play.api.libs.json.JsResult$class.fold(JsResult.scala:73) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]
        at play.api.libs.json.JsError.fold(JsResult.scala:13) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]
        at play.api.libs.json.JsReadable$class.as(JsReadable.scala:18) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]
[error] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(List(error.expected.jsarray),WrappedArray())))))
        at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:20) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]
        at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:20) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]
        at play.api.libs.json.JsResult$class.fold(JsResult.scala:73) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]
        at play.api.libs.json.JsError.fold(JsResult.scala:13) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]
        at play.api.libs.json.JsReadable$class.as(JsReadable.scala:18) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]
[error] application -

! @732bii8nf - Internal server error, for (POST) [/cluster_changes] ->

play.api.UnexpectedException: Unexpected exception[JsResultException: JsResultException(errors:List((,List(ValidationError(List(error.expected.jsarray),WrappedArray())))))]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:261) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.6.jar:2.4.6]
Caused by: play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(List(error.expected.jsarray),WrappedArray())))))
        at play.api.libs.json.JsReadable$$anonfun$2.apply(JsReadable.scala:20) ~[com.typesafe.play.play-json_2.11-2.4.6.jar:2.4.6]

```

**Comment by lmenezes** [comment]
I guess your cluster running 5.0 has authentication?

**Comment by hesmaeili** [comment]
I have a local installation for development purposes. I turned off the authentication on Elasticsearch and Kibana and put only localhost:9200 in Cerebro's configuration file. opening localhost:9000 does not throw any exception but it is always in a yellow state. I can create index but using any kind of GET throws the same exception.

**Comment by lmenezes** [comment]
If the error you get is still the same, it's just still "secured"(using x-pack?).
Did you configure that to use authentication(user/password)?

**Comment by hesmaeili** [comment]
I have x-pack security shut down for both Kibana 5.1.2 and Elasticsearch 5.2 'xpack.security.enabled: false'. Now these two communicate without the need of authentification. And I am using Cerebro with this configuration. in the application.conf file I have the following: 

hosts = [
  #{
  #  host = "http://some-authenticated-host:9200",
  #  auth = {
  #    username = "username"
  #    password = "secret-password"
  #  }
  #},
  {
    host = "http://localhost:9200"
  }
]

**Comment by lmenezes** [comment]
but based on the response you copied above, it still complains about missing authentication, so not really sure what might be wrong there, but its still requiring authentication information.

**Comment by hesmaeili** [comment]
Yes it does require. I also tested with the default username "elastic" and password "changeme" of Elasticsearch. It gives me the same auth problem...

**Comment by hesmaeili** [comment]
I have another question regarding this. Now also on ES 2.X I always have a yellow state in Cerebro. What might I be doing wrong?

**Comment by lmenezes** [comment]
When you do try using a password, what error do you see on the logs?

**Comment by lmenezes** [comment]
@hesmaeili is this still an issue?

**Comment by hesmaeili** [comment]
Honestly I have left the issue unsolved. I am busy with some project and I will have to get back to it later. But I believe it is open. Thanks for asking!

**Comment by hesmaeili** [comment]
So I came back to this issue after a while. It is working with the latest 5.4
thx very much
