### ISSUE TITLE
play.i18n.langs has type STRING rather than LIST

### ISSUE THREAD

**Issue by 20988902** [lmenezes/cerebro#93]
ES: v5.2.1
cerebro: v0.6.0
**I use v0.6.0, start it,has error:**

5) Error injecting constructor, com.typesafe.config.ConfigException$WrongType: application.conf @ file:/opt/cerebro-0.6.0/conf/application.conf: 12: play.i18n.langs has type STRING rather than LIST
  at play.api.i18n.DefaultLangs.<init>(Messages.scala:166)
  at play.api.i18n.DefaultLangs.class(Messages.scala:166)
  while locating play.api.i18n.DefaultLangs
  while locating play.api.i18n.Langs
    for parameter 2 at play.api.i18n.DefaultMessagesApi.<init>(Messages.scala:482)
  at play.api.i18n.DefaultMessagesApi.class(Messages.scala:482)
  while locating play.api.i18n.DefaultMessagesApi
Caused by: com.typesafe.config.ConfigException$WrongType: application.conf @ file:/opt/cerebro-0.6.0/conf/application.conf: 12: play.i18n.langs has type STRING rather than LIST
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:170)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:176)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:184)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:252)
	at com.typesafe.config.impl.SimpleConfig.getHomogeneousUnwrappedList(SimpleConfig.java:323)
	at com.typesafe.config.impl.SimpleConfig.getStringList(SimpleConfig.java:381)
	at play.api.ConfigLoader$$anonfun$6$$anonfun$apply$8.apply(Configuration.scala:1038)
	at play.api.ConfigLoader$$anonfun$6$$anonfun$apply$8.apply(Configuration.scala:1038)
	at play.api.ConfigLoader$$anon$3.load(Configuration.scala:1030)
	at play.api.ConfigLoader$$anon$2.load(Configuration.scala:1022)

**Comment by dekhtyarev** [comment]
I fix this by: `play.i18n.langs=["en"]`

But it was very surprising ..

**Comment by 20988902** [comment]
Thanks for helping

**Comment by lmenezes** [comment]
this has been fixed in v0.6.1. sorry for the trouble :)
