### ISSUE TITLE
Cerebro-0.6.0 -- error when REST _cat/health

### ISSUE THREAD

**Issue by seapasulli** [lmenezes/cerebro#95]
When I try to issue any rest gets/puts/ I seem to get errors. When I try to rest query _cat/health an error is logged::

`[error] application - `
`! @73afp42ek - Internal server error, for (POST) [/rest/request] ->
play.api.UnexpectedException: Unexpected exception[JsonParseException: Unexpected character (':' (code 58)): Expected space separating root-level values
 at [Source: [B@77374543; line: 1, column: 15]]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character (':' (code 58)): Expected space separating root-level values
 at [Source: [B@77374543; line: 1, column: 15]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:450)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportMissingRootWS(ParserMinimalBase.java:466)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._verifyRootSpace(UTF8StreamJsonParser.java:1657)`

**Comment by lmenezes** [comment]
@seapasulli hey. The rest client isn't really meant to handle non JSON apis(although I must admit, it could handle this better). You have two options: either use format=json on the call(and then it should just work), or just accusing the cat api from the cat module on the application itself.
